# Generated by Django 5.2.15 on 2026-07-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown event type'), ('created', 'Create Event'), ('viewed', 'View Event'), ('saved', 'Saved or Update Event')], default='viewed', max_length=40),
        ),
    ]
